[package]
name = "tink-ffi-sys"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/winstanley-industries/tink-ffi"
links = "tink"
description = "Raw FFI bindings to Google Tink via C shim"

[build-dependencies]
cmake = "0.1"
